### ISSUE TITLE
python 3.7 compatibility

### ISSUE THREAD

**Issue by xgdgsc** [discretelogics/TeaFiles.Py#4]
please merge from 
https://github.com/nikhgupta/TeaFiles.Py

**Comment by thulka** [comment]
Thank you for the link.
I added a link to your Python 3.7 version in the ReadMe. Is that ok for you?

**Comment by xgdgsc** [comment]
That' s not mine. I just looked through forks. I' m ok with anything.

**Comment by thulka** [comment]
ah, i see!
thank you.
